services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ../..:/workspaces:cached
      - ../../vsc-extensions:/vsc-extensions
      - ../../flogo-extensions:/flogo-extensions
    command: sleep infinity
    network_mode: service:azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
